mod_h2/h2_session.c, mod_h2/h2_util.c
Although nghttp2 API lists NGHTTP2_CONTINUATION in nghttp2_frame_type,
it won't be passed to any callbacks.  This is because the library
processes preceding HEADERS/PUSH_RPOMISE and following CONTINUATION
frames as single frame.
=> Remove NGHTTP2_CONTINUATION

sandbox/test/conf/httpd.conf
SSLProtocol definition inverted, so that future protocols such as TLSv1.3 will be automatically used.
=> Future proof SSLProtocol definition

mod_h2/h2_config.c
For me, this avoids a crash in ap_update_vhost_from_headers() but
it's unclear to me if ap_update_vhost_from_headers() is really
doing anything for us if the request data is all dummied anyway.
(don't get too excited, I was only trying to kick the tires. Also I'm not really a git or github user so bare with me)
=> initialize r->server like ap_read_request would

configure.ac
The == operator does not exist in POSIX (it's a feature some shells like
bash adds), so use = instead to work with all standard shells.
=> fix test commands to match POSIX

setup/Makefile.am
Makefile invokes bash whereas the script executed uses #!/bin/sh shebang. This fails on platforms that do not ship with bash.
=> Use plain shell

setup/install-config.sh
H2Engine directive was removed in https://github.com/Sp1l/mod_h2/commit/6765fad7ca5f80ade010e5db1093cfcc259bdff9
=> Remove H2Engine directive from install message

mod_http2/h2_push.c
This fixes building on both i386 and amd64.
Culprit and fix both in include/apr-1/apr.h
```
#ifdef __LP64__
...
typedef  unsigned long   apr_uint64_t;
...
#else
...
typedef  unsigned long long   apr_uint64_t;
...
#endif
```
The fix is also in there
```
#ifdef __LP64__
...
#define APR_UINT64_T_FMT     "lu"
...
#else
...
#define APR_UINT64_T_FMT     "llu"
...
#endif
```
=> Properly fix build on i386

mod_http2/h2_bucket_beam.c, mod_http2/h2_util.c
@icing This fixes compilatiion with Apache httpd 2.4.20
There was a redefinition in h2_bucket_beam.c as well. Line 106 redefined h2_bucket_type_beam in line 36:
.\h2_bucket_beam.c(106): error C2370: 'h2_bucket_type_beam' : redefinition; different storage class
.\h2_bucket_beam.c(106): error C2491: 'h2_bucket_type_beam' : definition of dllimport data not allowed
Note: in the mod_http2.dsp of the Apache sources h2_bucket_beam.c has to be added.
=> #99 Fix compilation with httpd 2.4.20

mod_http2/Makefile.am
Apply the libtool magic which only exposes the _module symbol, as is done for the in-tree mod_http2 build.
=> Restrict external symbols as in modules/http2 builds.

mod_http2/h2_proxy_util.c
GCC 8.x gives warnings on strncpy() usage since it might not NUL-terminate.
apr_cpystrn() is generally preferred in httpd code and can slightly simplify the code, since it guarantees to NUL-terminate, and like GNU stpcpy() it returns a pointer to the NUL terminator. 
I can't find tests cases for Link mapping so I haven't tested this sorry :(
Another option for subst_str() is to use apr_pstrcatv() which may or may not simplify the logic a bit.
=> Fix warnings/errors with GCC 8.x around strncpy usage, and simplify

mod_http2/mod_proxy_http2.c
mod_proxy_http2.c: In function 'proxy_http2_handler':
mod_proxy_http2.c:460:12: error: 'status' may be used uninitialized in this function [-Werror=maybe-uninitialized]
if (status != APR_SUCCESS) {
^
=> Fix GCC warning if first "goto cleanup" branch is taken.

mod_http2/h2_headers.c
When accessing a location that needs a client certificate, a downgrade
to HTTP 1.1 may be necessary if the current connection uses HTTP/2.
This must be done because HTTP/2 does not allow SSL renegotiations.
mod_h2 already handles this case, it sets a request note
"ssl-renegotiate-forbidden" and later evaluates it in
h2_headers_rcreate(). An RST_STREAM is sent to the client with the
error code HTTP_1_1_REQUIRED.
This did not work if there are custom error pages configured with
ErrorDocument. To show these error pages, Apache creates an internal
redirection in ap_die_r(). This creates a new internal request which
does not have the "ssl-renegotiate-forbidden" note.
Bugfix: Also look for the request note in linked requests.
Fixes #172
=> Support downgrade to HTTP 1.1 for subrequests

mod_http2/h2_private.h
12/19 *.c files use strcmp or strcpy.
On my AIX system, the linker gets confused and looks for strcmp and
friends in libssl (confirmed with dump -tv).
Since APR already has an APR_HAVE macro for string.h, just include
it from h2_private.h
=> include string.h for via h2_private

mod_http2/h2_stream.c
Log violations of LimitRequestFieldSize and LimitRequestFields only once per request (same behavior as for HTTP 1.x)
Without this change, up to 100 log messages per request are possible.
=> Log too long/too many headers only once per request

Makefile.am
create tests/Makefile.am.
Hi Stefan,
I was trying to build and run upstream test suite from dist tarball, but when I was trying to run "make test", it will fail since Makefile.am is needed as dependency:
$ make test >test.output'
make[1]: *** No rule to make target 'Makefile.am', needed by 'Makefile.in'.  Stop.
make: *** [Makefile:923: test] Error 2
I can workaround it by:
$ touch test/Makefile.am
$ touch test/Makefile.in
$ make test
but anyway, when I want to make some changes in Makefile.am and regenerate it, I can't do so.
=> Distribute Makefile.am, so tests are executable without need to

test/e2e/TestEnv.py, test/e2e/TestNghttp.py
The capture_output arg in subprocess.run is available
only for Python 3.7, meanwhile the version with PIPE
is compatible with more versions (3.5+ mostly).
This allows to run the test suite in multiple platforms,
especially the ones without Python 3.7.
issue: #185
=> test: replace capture_output with subprocess.PIPE

test/e2e/TestEnv.py, test/e2e/test_003_get.py
- test_003_get.py
* force curl to use tls1.2+
* allow TLS 1.3 as result
- TestEnv.py
* shut off a warning for configparser.SafeConfigParser
* replace subprocess' text=true with universal_newlines=True
=> Some improvements to the Python test suite

mod_http2/h2_bucket_beam.c, mod_http2/h2_bucket_beam.h
Not sure why but I'm seeing gcc 10 warnings on s390x (only) for this.
```
h2_bucket_beam.c: In function 'h2_beam_abort':
h2_bucket_beam.c:222:9: error: 'bl.leave_ctx' may be used uninitialized in this function [-Werror=maybe-uninitialized]
222 |         pbl->leave(pbl->leave_ctx, pbl->mutex);
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
h2_bucket_beam.c:710:18: note: 'bl.leave_ctx' was declared here
710 |     h2_beam_lock bl;
|                  ^~
h2_bucket_beam.c: In function 'h2_beam_close':
h2_bucket_beam.c:222:9: error: 'bl.leave_ctx' may be used uninitialized in this function [-Werror=maybe-uninitialized]
222 |         pbl->leave(pbl->leave_ctx, pbl->mutex);
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Remove unused leave_ctx from h2_beam_lock structure and adjust callers.

mod_http2/h2_util.c
This is triggered running t/modules/http2.t from the perl framework when built under 
`gcc -fsanitize=undefined` if it's surprising to get here with len=0 lmk and I can debug further.
=> Avoid triggering UBSan with memcpy(,NULL,0).

mod_http2/h2_session.c
After `h2_session_open_stream(session, nid, is->id)` returns NULL, don't reference it via H2_STRM_LOG(), using "is" instead is appropriate I assume?
```
In file included from h2_session.c:28:
h2_session.c: In function ‘h2_session_push’:
/usr/include/httpd/http_log.h:498:23: warning: null pointer dereference [-Wnull-dereference]
498 | #define ap_log_cerror ap_log_cerror_
h2_session.c:1181:9: note: in expansion of macro ‘ap_log_cerror’
1181 |         ap_log_cerror(APLOG_MARK, APLOG_DEBUG, 0, session->c,
|         ^~~~~~~~~~~~~
In file included from h2_session.c:45:
h2_stream.h:309:35: warning: null pointer dereference [-Wnull-dereference]
309 |     "h2_stream(%ld-%d,%s): "msg, s->session->id, s->id, h2_stream_state_str(s)
h2_stream.h:311:49: note: in expansion of macro ‘H2_STRM_MSG’
311 | …
```
=> Fix gcc warning for H2_STRM_LOG() use in h2_session_push.

test/e2e/TestEnv.py, test/e2e/test_006_assets.py
if there is some output on stderr when nghttp -a is executed, skip tests where -a param is used.
=> In case, nghttp is ignoring -a param, skip tests.

mod_http2/h2_push.c
Not sure if the test suite is exercising this code directly, so may be untested.  FWIW I get the same four failures running "make test" against httpd trunk on Fedora 34 with and without this patch.
```
============================================== short test summary info ==============================================
FAILED test_101_ssl_reneg.py::TestStore::test_101_02 - assert 0 != 0
FAILED test_101_ssl_reneg.py::TestStore::test_101_11 - assert 0 != 0
FAILED test_105_timeout.py::TestStore::test_105_01 - assert False
FAILED test_105_timeout.py::TestStore::test_105_02 - assert False
```
=> Switch to using OpenSSL EVP_* API to avoid deprecation warnings with OpenSSL 3.0.

mod_http2/h2_config.c, mod_http2/h2_config.h, mod_http2/mod_http2.c
Add H2BeamTimeout directive in order to set separate beam timeouts
per requests. If not set defaults to the timeout value of the virtual
host.
* mod_http2/h2_config.c: Setup H2BeamTimeout config directive handling.
* mod_http2/h2_config.h: Setup H2BeamTimeout config directive handling.
* mod_http2/mod_http2.c: Set the beam timeout in the fixup hook.
=> Add H2BeamTimeout directive

ChangeLog, mod_http2/h2.h, mod_http2/h2_c2.c, mod_http2/h2_c2_filter.c, mod_http2/h2_conn_ctx.h, mod_http2/h2_mplx.c, mod_http2/h2_push.c, mod_http2/h2_request.c, mod_http2/h2_request.h, mod_http2/h2_stream.c, mod_http2/h2_stream.h
* Delaying input setup of a stream just before processing starts. This allows any EOS indicator arriving from the client before that to take effect. Without knowing that a stream has no input, internal processing has to simulate chunked encoding. This is not wrong, but somewhat more expensive and mod_security has been reported to be allergic to seeing 'chunked' on some requests. See <https://bz.apache.org/bugzilla/show_bug.cgi?id=66282>.
=> Improvement on stream input handling

ChangeLog, mod_http2/h2_config.c, mod_http2/h2_config.h, mod_http2/h2_session.c, mod_http2/h2_session.h, mod_http2/h2_stream.c, test/modules/http2/test_107_frame_lengths.py, test/pyhttpd/nghttp.py
* New directive 'H2MaxDataFrameLen n' to limit the maximum amount of response body bytes put into a single HTTP/2 DATA frame. Setting this to 0 places no limit (but the max size allowed by the protocol is observed). The module, by default, tries to use the maximum size possible, which is somewhat around 16KB. This sets the maximum. When less response data is availble, smaller frames will be sent.
=> H2MaxDataFrameLen added incl test cases.

mod_http2/h2_bucket_beam.c, mod_http2/h2_bucket_beam.h, mod_http2/h2_c2.c, mod_http2/h2_conn_ctx.h, mod_http2/h2_mplx.c, mod_http2/h2_stream.c, test/modules/http2/test_008_ranges.py, test/pyhttpd/env.py
Accurately report the bytes sent for a request in the '%O' Log format.
This addresses #203, a long outstanding issue where mod_h2 has reported
numbers over-eagerly from internal buffering and not what has actually
been placed on the connection.
The numbers are now the same with and without H2CopyFiles enabled.
=> fix for logio reported bytes sent

ChangeLog, mod_http2/h2_c2.c, mod_http2/h2_c2_filter.c, mod_http2/h2_config.c, mod_http2/h2_config.h, mod_http2/h2_headers.c, mod_http2/h2_stream.c, test/modules/http2/test_401_early_hints.py
New directive 'H2EarlyHint name value' to add headers to a response,
picked up already when a "103 Early Hints" response is sent. 'name' and
'value' must comply to the HTTP field restrictions.
This directive can be repeated several times and header fields of the
same names add. Sending a 'Link' header with 'preload' relation will
also cause a HTTP/2 PUSH if enabled and supported by the client.
=> New directive 'H2EarlyHint'

ChangeLog, mod_http2/h2_proxy_session.c, test/modules/http2/env.py, test/modules/http2/test_003_get.py, test/modules/http2/test_004_post.py, test/modules/http2/test_104_padding.py, test/modules/http2/test_500_proxy.py
On detecting that that an existing connection was shutdown by the other
side, a 503 response leaked even though the request was retried on a
fresh connection.
=>  * mod_proxy_http2: fix retry handling to not leak temporary errors.

mod_http2/mod_proxy_http2.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -std=c99 -D_GNU_SOURCE -Werror -I/usr/include/httpd -I/usr/include/apr-1 -DLINUX -D_REENTRANT -D_GNU_SOURCE -DH2_NG2_STREAM_API -DH2_NG2_CHANGE_PRIO -DH2_NG2_INVALID_HEADER_CB -DH2_NG2_LOCAL_WIN_SIZE -DH2_NG2_NO_CLOSED_STREAMS -DH2_NG2_RFC9113_STRICTNESS -DH2_OPENSSL -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/generic-hardened-cc1 -fasynchronous-unwind-tables -fstack-clash-protection -c mod_proxy_http2.c  -fPIC -DPIC -o .libs/mod_proxy_http2_la-mod_proxy_http2.o
mod_proxy_http2.c: In function 'proxy_http2_canon':
mod_proxy_http2.c:161:30: error: unused variable 'd' [-Werror=unused-variable]
161 |             core_dir_config *d = …
=> fix compilation error when using PROXY_CANONENC_NOENCODEDSLASHENCODING

.gitignore, ChangeLog, mod_http2/h2_c1.c, mod_http2/h2_mplx.c, mod_http2/h2_mplx.h, mod_http2/h2_session.c, mod_http2/h2_session.h, test/conftest.py, test/modules/http2/test_700_load_get.py
* When flow control to the client blocks, needing a WINDOW_UPDATE to make
further progress, HTTP/2 connection processing returns to the MPM.
If using "mpm_event", this will free a worker.
=> async processing on client flow block

mod_http2/h2_c2.c, mod_http2/h2_session.c, test/pyhttpd/curl.py
- only enable on newer HTTPD versions. 2.4.x versions still treat connections in the event MPM as KeepAlive and purge them on load.
- spelling fixes
- support for yield calls in c2 "network" filter
=> async block handling

ChangeLog, README.md, configure.ac, mod_http2/h2_config.c, mod_http2/h2_config.h, mod_http2/h2_mplx.c, mod_http2/h2_session.c, mod_http2/h2_session.h, mod_http2/h2_util.c, mod_http2/h2_version.h
Add directive `H2MaxStreamErrors` to control connection close when client behaves badly. 
With a default of 8, a connection is shut down after 8 client caused stream errors happened. This currently counts violation of HTTP/2 flow control and may extend to other situations in the future.
Set to 0 to disable this trigger.
=> H2MaxStreamErrors directive
